[tool.black]
line-length = 120
exclude = '''
/(
    migrations
    | __pycache__
    | settings\.py
)/
'''

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
known_third_party = ["django", "rest_framework"]
